# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-24 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_meter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data_meter',
            options={'verbose_name': 'Данные счетчика', 'verbose_name_plural': 'Данные счетчиков'},
        ),
    ]
