# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-28 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_meter', '0002_auto_20171024_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_meter',
            name='tariff',
        ),
        migrations.RemoveField(
            model_name='data_meter',
            name='type_resource',
        ),
        migrations.AddField(
            model_name='data_meter',
            name='type_meter',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Вид счетчика'),
        ),
        migrations.AlterField(
            model_name='data_meter',
            name='accounting_period',
            field=models.DateField(auto_now_add=True, verbose_name='Период учета'),
        ),
    ]
