# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-28 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_meter', '0003_auto_20171029_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_meter',
            name='accounting_period',
            field=models.DateField(verbose_name='Период учета'),
        ),
    ]
