# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-28 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_meter', '0004_auto_20171029_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_meter',
            name='accounting_period',
        ),
        migrations.AddField(
            model_name='data_meter',
            name='accounting_month',
            field=models.IntegerField(help_text='Введите месяц учёта', null=True, verbose_name='Месяц учета'),
        ),
        migrations.AddField(
            model_name='data_meter',
            name='accounting_year',
            field=models.IntegerField(help_text='Введите год учёта', null=True, verbose_name='Год учета'),
        ),
    ]
