# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-01 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_meter', '0007_data_meter_type_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_meter',
            name='dannie',
            field=models.IntegerField(default=1, verbose_name='Показание прибора'),
            preserve_default=False,
        ),
    ]
