# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-24 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_resource', models.CharField(max_length=15, verbose_name='Вид ресурса')),
                ('tariff', models.CharField(max_length=15, verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Вид счетчика',
                'verbose_name_plural': 'Виды счетчиков',
            },
        ),
    ]
