# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-24 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='tariff',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Тариф'),
        ),
    ]
