# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-28 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meter', '0002_auto_20171024_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='tariff',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='type_resource',
        ),
        migrations.AddField(
            model_name='meter',
            name='type_meter',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Вид счетчика'),
        ),
    ]
