# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-28 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meter', '0003_auto_20171028_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='codes',
            field=models.CharField(default='', max_length=10, verbose_name='Код счетчика'),
        ),
    ]
