# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-29 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meter', '0007_auto_20171029_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='code_type_meter',
            field=models.CharField(max_length=10, verbose_name='Код счетчика'),
        ),
    ]
