# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-01 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meter', '0008_auto_20171030_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='code_type_meter',
            field=models.CharField(blank=True, max_length=10, verbose_name='Код счетчика'),
        ),
    ]
