# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-01 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meter', '0009_auto_20171101_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='code_type_meter',
        ),
    ]
